# Generated by Axiom CLI — do not delete.
# Ensures pytest can resolve "from nodes.<module> import <func>" imports
# whether tests are run from the package root or inside the Docker build.
import sys, os as _os
sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))

import pytest

_FIXTURE_DIR = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)), "fixtures")


def _load_fixture(name: str) -> bytes:
    """Read the raw bytes of a committed fixture image (nodes/fixtures/<name>)."""
    with open(_os.path.join(_FIXTURE_DIR, name), "rb") as fh:
        return fh.read()


@pytest.fixture
def fixture_bytes():
    """Factory that returns the bytes of a committed fixture image by name.

    The fixtures carry KNOWN text baked in at authoring time (independent of
    RapidOCR), so asserting the recognized text against that known ground truth
    is a genuine independent-oracle check, not a round-trip against the library.
    """
    return _load_fixture


class _TestContext:
    """Minimal AxiomContext stand-in for unit tests (nodes here don't use it)."""

    class _Logger:
        def debug(self, msg: str, **attrs) -> None: pass
        def info(self, msg: str, **attrs) -> None: pass
        def warn(self, msg: str, **attrs) -> None: pass
        def error(self, msg: str, **attrs) -> None: pass

    class _Secrets:
        def __init__(self, m: dict) -> None:
            self._m = m or {}
        def get(self, name: str):
            v = self._m.get(name)
            return (v, True) if v is not None else ("", False)

    def __init__(self, secrets_map: dict | None = None) -> None:
        self.log = self._Logger()
        self.secrets = self._Secrets(secrets_map or {})
        self.execution_id = "test-execution-id"
        self.flow_id = "test-flow-id"
        self.tenant_id = "test-tenant-id"


@pytest.fixture
def ax():
    """A minimal AxiomContext for invoking nodes in tests."""
    return _TestContext()
